#include "spi_flash.h"


void SPI_FLASH_Init(void)
{
	CLK_EnableModuleClock(SPIM_MODULE);
	SYS->GPA_MFPL|=SYS_GPA_MFPL_PA0MFP_SPIM_MOSI;
	SYS->GPA_MFPL|=SYS_GPA_MFPL_PA1MFP_SPIM_MISO;
	SYS->GPA_MFPL|=SYS_GPA_MFPL_PA2MFP_SPIM_CLK;
	SYS->GPA_MFPL|=SYS_GPA_MFPL_PA3MFP_SPIM_SS;
	SYS->GPA_MFPL|=SYS_GPA_MFPL_PA4MFP_SPIM_D3;
	SYS->GPA_MFPL|=SYS_GPA_MFPL_PA5MFP_SPIM_D2;
	GPIO_SetSlewCtl(PA, BIT0, GPIO_SLEWCTL_FAST);
	GPIO_SetSlewCtl(PA, BIT1, GPIO_SLEWCTL_FAST);
	GPIO_SetSlewCtl(PA, BIT2, GPIO_SLEWCTL_FAST);
	GPIO_SetSlewCtl(PA, BIT3, GPIO_SLEWCTL_FAST);
	GPIO_SetSlewCtl(PA, BIT4, GPIO_SLEWCTL_FAST);
	GPIO_SetSlewCtl(PA, BIT5, GPIO_SLEWCTL_FAST);
	SPIM_SET_CLOCK_DIVIDER(3);	//DIVIDER=3	SPICLK=HCLK/(DIVIDER*2)
//	SPIM->CTL0&=0xCFFFFF;				//CMDCODE=0	BITMODE=0
//	SPIM->CTL0|=0xEB<<24;				//CMDCODE=0xEB
//	SPIM->CTL0|=0x2<<20;				//BITMODE=0x2
	SPIM->CTL1&=~SPIM_CTL1_SSACTPOL_Msk;				//SSACTPOL=0
	SPIM->CTL0&=~SPIM_CTL0_OPMODE_Msk;					//OPMODE=0
	SPIM->CTL0&=~SPIM_CTL0_BURSTNUM_Msk;		//BURSTNUM=0
	SPIM->CTL0&=~SPIM_CTL0_DWIDTH_Msk;			//DWIDTH=0
	SPIM->CTL0|=0x07<<SPIM_CTL0_DWIDTH_Pos;	//DWIDTH=0x07
}


u8 SPIM_SendByte(u8 data)
{
//	while(SPIM->CTL1&SPIM_CTL1_SPIMEN_Msk);
//	SPIM->CTL0|=SPIM_CTL0_QDIODIR_Msk;			//QDIODIR=1
//	SPIM->TX[0]=data;
//	
//	SPIM->CTL1|=SPIM_CTL1_SPIMEN_Msk;				//SPIMEN=1
//	while(SPIM->CTL1&SPIM_CTL1_SPIMEN_Msk);
//	
//	SPIM->CTL0&=~SPIM_CTL0_QDIODIR_Msk;			//QDIODIR=0
//	SPIM->CTL1|=SPIM_CTL1_SPIMEN_Msk;				//SPIMEN=1
//	while(SPIM->CTL1&SPIM_CTL1_SPIMEN_Msk);
	
	return(SPIM->RX[0]);
	
}




