#include "usart.h"


void uart_init(u32 bound)//PB12:UART0_RX		PB13:UART0_TX
{
	CLK_SetModuleClock(UART0_MODULE,CLK_CLKSEL1_UART0SEL_HXT,CLK_CLKDIV0_UART0(1));		//设置时钟源
	CLK->APBCLK0 |= CLK_APBCLK0_UART0CKEN_Msk;																				//打开UART0时钟
	SYS->GPB_MFPH&=~(SYS_GPB_MFPH_PB12MFP_UART0_RXD|SYS_GPB_MFPH_PB13MFP_UART0_TXD);		//清除PB12MFP PB13MFP位
	SYS->GPB_MFPH|=SYS_GPB_MFPH_PB12MFP_UART0_RXD|SYS_GPB_MFPH_PB13MFP_UART0_TXD;				//设置PB12MFP PB13MFP为MFP
	UART_SetLineConfig(UART0, 115200, UART_WORD_LEN_8, UART_PARITY_NONE, UART_STOP_BIT_1);
}






